<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN3317377"><DocLocation><![CDATA[C:\Framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\gourmet_garden1]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[gourmet_garden1]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Organic & Naturoponic]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:31]]></Time>
<TimeTick>1676350111</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Organic & Naturoponic]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:31]]></Time>
<TimeTick>1676350111</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[MY ACCOUNT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:31]]></Time>
<TimeTick>1676350111</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="login" SourceLine="0" >
<Disp><![CDATA[MY ACCOUNT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:31]]></Time>
<TimeTick>1676350111</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" Source="login" SourceLine="1" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="login" SourceLine="0" >
<Disp><![CDATA[Organic & Naturoponic]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Account]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:33]]></Time>
<TimeTick>1676350113</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[customer[email].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["sangeetha6617@gmail.com"]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:33]]></Time>
<TimeTick>1676350113</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="login" SourceLine="2" >
<Disp><![CDATA[customer[email].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[customer[password].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63eb10ebd0839844eb946fd840de48408873c1184b16d7a1600859a2750d"]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:33]]></Time>
<TimeTick>1676350113</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="login" SourceLine="3" >
<Disp><![CDATA[customer[password].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Sign In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:33]]></Time>
<TimeTick>1676350113</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" Source="login" SourceLine="4" >
<Disp><![CDATA[Sign In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" Source="login" SourceLine="2" >
<Disp><![CDATA[Account]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Account_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:36]]></Time>
<TimeTick>1676350116</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Gourmet Garden.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:36]]></Time>
<TimeTick>1676350116</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" Source="login" SourceLine="5" >
<Disp><![CDATA[Gourmet Garden.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" Source="login" SourceLine="5" >
<Disp><![CDATA[Account_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="login" SourceLine="0" >
<Disp><![CDATA[Organic & Naturoponic]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 10:18:31" eTime="14-02-2023 - 10:18:36" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[Search]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[freshly cut - Gourmet]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:38]]></Time>
<TimeTick>1676350118</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[freshly cut - Gourmet]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:38]]></Time>
<TimeTick>1676350118</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Search our store.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["freshly cut"]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:38]]></Time>
<TimeTick>1676350118</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" Source="Search" SourceLine="0" >
<Disp><![CDATA[Search our store.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[bottlegourddiced_895b6697-9075.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:39]]></Time>
<TimeTick>1676350119</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="Search" SourceLine="1" >
<Disp><![CDATA[bottlegourddiced_895b6697-9075.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" Source="Search" SourceLine="0" >
<Disp><![CDATA[freshly cut - Gourmet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Bottle Gourd - Cut]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:46]]></Time>
<TimeTick>1676350126</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Add to cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:18:46]]></Time>
<TimeTick>1676350126</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Search" SourceLine="2" >
<Disp><![CDATA[Add to cart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["1"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:08]]></Time>
<TimeTick>1676350148</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" status="Warning" Source="Search" SourceLine="3" >
<Disp><![CDATA["1"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["1"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=1<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (285 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=1<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 285 matches)</SPAN><br>class=site-header__link_cart<SPAN class=Failed> (Skipped)</SPAN><br>name=1<SPAN class=Failed> (Skipped)</SPAN><br>href=https://gourmetgarden.in/cart<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:08]]></Time>
<TimeTick>1676350148</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="84" Source="Search" SourceLine="3" >
<Disp><![CDATA["1"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:08]]></Time>
<TimeTick>1676350148</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" Source="Search" SourceLine="3" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="42" status="Warning" Source="Search" SourceLine="2" >
<Disp><![CDATA[Bottle Gourd - Cut]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Your Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:13]]></Time>
<TimeTick>1676350153</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Gourmet Garden.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:13]]></Time>
<TimeTick>1676350153</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" Source="Search" SourceLine="6" >
<Disp><![CDATA[Gourmet Garden.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="88" Source="Search" SourceLine="6" >
<Disp><![CDATA[Your Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" status="Warning" Source="Search" SourceLine="0" >
<Disp><![CDATA[freshly cut - Gourmet]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 10:18:36" eTime="14-02-2023 - 10:19:13" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="31" status="Warning" >
<Disp><![CDATA[Search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T27">
<AName><![CDATA[logout]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Organic & Naturoponic]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:17]]></Time>
<TimeTick>1676350157</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Organic & Naturoponic]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:17]]></Time>
<TimeTick>1676350157</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[MY ACCOUNT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:17]]></Time>
<TimeTick>1676350157</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" Source="logout" SourceLine="0" >
<Disp><![CDATA[MY ACCOUNT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Logout.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:17]]></Time>
<TimeTick>1676350157</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="99" Source="logout" SourceLine="1" >
<Disp><![CDATA[Logout.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[YES.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 10:19:18]]></Time>
<TimeTick>1676350158</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="102" Source="logout" SourceLine="2" >
<Disp><![CDATA[YES.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="95" Source="logout" SourceLine="0" >
<Disp><![CDATA[Organic & Naturoponic]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="94" Source="logout" SourceLine="0" >
<Disp><![CDATA[Organic & Naturoponic]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 10:19:13" eTime="14-02-2023 - 10:19:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="91" >
<Disp><![CDATA[logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[gourmet_garden1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 10:18:24" eTime="14-02-2023 - 10:19:18" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test gourmet_garden1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>